CREATE USER ${DB_REPL_USER} REPLICATION LOGIN PASSWORD '${DB_REPL_PASSWORD}';
CREATE DATABASE ${DB_DATABASE};
\c ${DB_DATABASE};

CREATE TABLE IF NOT EXISTS Phones (phoneID SERIAL PRIMARY KEY, phone VARCHAR(16));
CREATE TABLE IF NOT EXISTS Emails (emailID SERIAL PRIMARY KEY, email VARCHAR(255));
